-- Snowflake setup for free-trial environment
-- Run in Snowflake worksheet with ACCOUNTADMIN or a role with equivalent grants.

CREATE WAREHOUSE IF NOT EXISTS STOCK_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS STOCK_DWH;

CREATE ROLE IF NOT EXISTS STOCK_DWH_ROLE;

GRANT USAGE ON WAREHOUSE STOCK_WH TO ROLE STOCK_DWH_ROLE;
GRANT USAGE ON DATABASE STOCK_DWH TO ROLE STOCK_DWH_ROLE;

USE DATABASE STOCK_DWH;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS DW;

GRANT USAGE ON ALL SCHEMAS IN DATABASE STOCK_DWH TO ROLE STOCK_DWH_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK
  ON ALL SCHEMAS IN DATABASE STOCK_DWH TO ROLE STOCK_DWH_ROLE;
