-- Core warehouse objects: staging + dim/fact

USE WAREHOUSE STOCK_WH;
USE DATABASE STOCK_DWH;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS DW;

-- Raw landing table (from Kafka connector, Snowpipe Streaming, or batch loader)
CREATE TABLE IF NOT EXISTS BRONZE.RAW_QUOTES (
  EVENT_TIME TIMESTAMP_TZ,
  INGEST_TIME TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  TICKER STRING,
  PRICE NUMBER(18,4),
  VOLUME NUMBER(38,0),
  CHANGE NUMBER(18,4),
  PERCENT_CHANGE NUMBER(12,6),
  HIGH NUMBER(18,4),
  LOW NUMBER(18,4),
  OPEN_PRICE NUMBER(18,4),
  CLOSE_PRICE NUMBER(18,4),
  QUOTE_TIME STRING,
  DATA_SOURCE STRING,
  KAFKA_TOPIC STRING,
  KAFKA_PARTITION NUMBER(10,0),
  KAFKA_OFFSET NUMBER(38,0),
  RAW_PAYLOAD VARIANT
);

CREATE TABLE IF NOT EXISTS SILVER.REALTIME_QUOTES_CLEAN (
  EVENT_TIME TIMESTAMP_TZ NOT NULL,
  INGEST_TIME TIMESTAMP_TZ NOT NULL,
  TICKER STRING NOT NULL,
  PRICE NUMBER(18,4) NOT NULL,
  VOLUME NUMBER(38,0) NOT NULL,
  CHANGE NUMBER(18,4),
  PERCENT_CHANGE NUMBER(12,6),
  HIGH NUMBER(18,4),
  LOW NUMBER(18,4),
  OPEN_PRICE NUMBER(18,4),
  CLOSE_PRICE NUMBER(18,4),
  DATA_SOURCE STRING,
  RECORD_HASH STRING,
  LOAD_TS TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DW.DIM_TICKER (
  TICKER_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  TICKER_CODE STRING NOT NULL,
  COMPANY_NAME STRING,
  EXCHANGE STRING,
  SECTOR STRING,
  INDUSTRY STRING,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  VALID_FROM TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  VALID_TO TIMESTAMP_TZ,
  IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT PK_DIM_TICKER PRIMARY KEY (TICKER_SK)
);

CREATE TABLE IF NOT EXISTS DW.DIM_DATE (
  DATE_SK NUMBER(8,0) NOT NULL,
  CALENDAR_DATE DATE NOT NULL,
  YEAR NUMBER(4,0) NOT NULL,
  QUARTER NUMBER(1,0) NOT NULL,
  MONTH NUMBER(2,0) NOT NULL,
  DAY NUMBER(2,0) NOT NULL,
  DAY_OF_WEEK NUMBER(1,0) NOT NULL,
  IS_WEEKEND BOOLEAN NOT NULL,
  CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_SK)
);

CREATE TABLE IF NOT EXISTS DW.FACT_QUOTE_1M (
  QUOTE_1M_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  TICKER_SK NUMBER NOT NULL,
  DATE_SK NUMBER(8,0) NOT NULL,
  BUCKET_MINUTE TIMESTAMP_TZ NOT NULL,
  OPEN_PRICE NUMBER(18,4),
  HIGH_PRICE NUMBER(18,4),
  LOW_PRICE NUMBER(18,4),
  CLOSE_PRICE NUMBER(18,4),
  VOLUME NUMBER(38,0),
  TURNOVER NUMBER(24,4),
  SOURCE_ROWS NUMBER(10,0),
  LOAD_TS TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FACT_QUOTE_1M PRIMARY KEY (QUOTE_1M_SK)
);

-- Optional query acceleration on common access patterns
ALTER TABLE SILVER.REALTIME_QUOTES_CLEAN CLUSTER BY (TO_DATE(EVENT_TIME), TICKER);
ALTER TABLE DW.FACT_QUOTE_1M CLUSTER BY (TO_DATE(BUCKET_MINUTE), TICKER_SK);
