-- Incremental modeling with stream + task:
-- BRONZE -> SILVER and SILVER -> FACT

USE WAREHOUSE STOCK_WH;
USE DATABASE STOCK_DWH;

CREATE OR REPLACE STREAM BRONZE.RAW_QUOTES_STREAM
  ON TABLE BRONZE.RAW_QUOTES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM SILVER.REALTIME_QUOTES_STREAM
  ON TABLE SILVER.REALTIME_QUOTES_CLEAN
  APPEND_ONLY = TRUE;

-- Merge into SILVER with lightweight quality filters + dedup key
CREATE OR REPLACE TASK SILVER.TASK_MERGE_QUOTES_TO_SILVER
  WAREHOUSE = STOCK_WH
  SCHEDULE = '1 MINUTE'
AS
MERGE INTO SILVER.REALTIME_QUOTES_CLEAN t
USING (
  SELECT
    EVENT_TIME,
    COALESCE(INGEST_TIME, CURRENT_TIMESTAMP()) AS INGEST_TIME,
    UPPER(TICKER) AS TICKER,
    PRICE,
    VOLUME,
    CHANGE,
    PERCENT_CHANGE,
    HIGH,
    LOW,
    OPEN_PRICE,
    CLOSE_PRICE,
    COALESCE(DATA_SOURCE, 'vnstock') AS DATA_SOURCE,
    SHA2(
      CONCAT_WS(
        '|',
        UPPER(TICKER),
        TO_VARCHAR(EVENT_TIME),
        TO_VARCHAR(PRICE),
        TO_VARCHAR(VOLUME)
      ),
      256
    ) AS RECORD_HASH
  FROM BRONZE.RAW_QUOTES_STREAM
  WHERE TICKER IS NOT NULL
    AND REGEXP_LIKE(TICKER, '^[A-Z]{2,5}$')
    AND PRICE > 0
    AND VOLUME >= 0
) s
ON t.TICKER = s.TICKER AND t.EVENT_TIME = s.EVENT_TIME
WHEN MATCHED THEN UPDATE SET
  INGEST_TIME = s.INGEST_TIME,
  PRICE = s.PRICE,
  VOLUME = s.VOLUME,
  CHANGE = s.CHANGE,
  PERCENT_CHANGE = s.PERCENT_CHANGE,
  HIGH = s.HIGH,
  LOW = s.LOW,
  OPEN_PRICE = s.OPEN_PRICE,
  CLOSE_PRICE = s.CLOSE_PRICE,
  DATA_SOURCE = s.DATA_SOURCE,
  RECORD_HASH = s.RECORD_HASH
WHEN NOT MATCHED THEN INSERT (
  EVENT_TIME, INGEST_TIME, TICKER, PRICE, VOLUME, CHANGE, PERCENT_CHANGE,
  HIGH, LOW, OPEN_PRICE, CLOSE_PRICE, DATA_SOURCE, RECORD_HASH
) VALUES (
  s.EVENT_TIME, s.INGEST_TIME, s.TICKER, s.PRICE, s.VOLUME, s.CHANGE, s.PERCENT_CHANGE,
  s.HIGH, s.LOW, s.OPEN_PRICE, s.CLOSE_PRICE, s.DATA_SOURCE, s.RECORD_HASH
);

-- Ensure current ticker rows exist in dimension (Type 1 baseline)
CREATE OR REPLACE TASK DW.TASK_UPSERT_DIM_TICKER
  WAREHOUSE = STOCK_WH
  AFTER SILVER.TASK_MERGE_QUOTES_TO_SILVER
AS
MERGE INTO DW.DIM_TICKER d
USING (
  SELECT DISTINCT TICKER
  FROM SILVER.REALTIME_QUOTES_STREAM
) s
ON d.TICKER_CODE = s.TICKER AND d.IS_CURRENT = TRUE
WHEN NOT MATCHED THEN INSERT (
  TICKER_CODE, COMPANY_NAME, EXCHANGE, SECTOR, INDUSTRY, IS_ACTIVE, VALID_FROM, IS_CURRENT
) VALUES (
  s.TICKER, NULL, NULL, NULL, NULL, TRUE, CURRENT_TIMESTAMP(), TRUE
);

-- Build 1-minute OHLCV fact incrementally
CREATE OR REPLACE TASK DW.TASK_BUILD_FACT_QUOTE_1M
  WAREHOUSE = STOCK_WH
  AFTER DW.TASK_UPSERT_DIM_TICKER
AS
MERGE INTO DW.FACT_QUOTE_1M f
USING (
  WITH base AS (
    SELECT
      DATE_TRUNC('MINUTE', EVENT_TIME) AS BUCKET_MINUTE,
      TICKER,
      MIN(EVENT_TIME) AS MIN_ET,
      MAX(EVENT_TIME) AS MAX_ET,
      MAX(HIGH) AS HIGH_PRICE,
      MIN(LOW) AS LOW_PRICE,
      SUM(VOLUME) AS VOLUME,
      SUM(PRICE * VOLUME) AS TURNOVER,
      COUNT(*) AS SOURCE_ROWS
    FROM SILVER.REALTIME_QUOTES_STREAM
    GROUP BY 1, 2
  )
  SELECT
    d.TICKER_SK,
    TO_NUMBER(TO_CHAR(CAST(b.BUCKET_MINUTE AS DATE), 'YYYYMMDD')) AS DATE_SK,
    b.BUCKET_MINUTE,
    o.PRICE AS OPEN_PRICE,
    b.HIGH_PRICE,
    b.LOW_PRICE,
    c.PRICE AS CLOSE_PRICE,
    b.VOLUME,
    b.TURNOVER,
    b.SOURCE_ROWS
  FROM base b
  JOIN SILVER.REALTIME_QUOTES_CLEAN o
    ON o.TICKER = b.TICKER AND o.EVENT_TIME = b.MIN_ET
  JOIN SILVER.REALTIME_QUOTES_CLEAN c
    ON c.TICKER = b.TICKER AND c.EVENT_TIME = b.MAX_ET
  JOIN DW.DIM_TICKER d
    ON d.TICKER_CODE = b.TICKER AND d.IS_CURRENT = TRUE
) s
ON f.TICKER_SK = s.TICKER_SK
AND f.BUCKET_MINUTE = s.BUCKET_MINUTE
WHEN MATCHED THEN UPDATE SET
  DATE_SK = s.DATE_SK,
  OPEN_PRICE = s.OPEN_PRICE,
  HIGH_PRICE = s.HIGH_PRICE,
  LOW_PRICE = s.LOW_PRICE,
  CLOSE_PRICE = s.CLOSE_PRICE,
  VOLUME = s.VOLUME,
  TURNOVER = s.TURNOVER,
  SOURCE_ROWS = s.SOURCE_ROWS,
  LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  TICKER_SK, DATE_SK, BUCKET_MINUTE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE,
  CLOSE_PRICE, VOLUME, TURNOVER, SOURCE_ROWS
) VALUES (
  s.TICKER_SK, s.DATE_SK, s.BUCKET_MINUTE, s.OPEN_PRICE, s.HIGH_PRICE, s.LOW_PRICE,
  s.CLOSE_PRICE, s.VOLUME, s.TURNOVER, s.SOURCE_ROWS
);

-- Enable root task only (downstream tasks trigger by dependency)
ALTER TASK SILVER.TASK_MERGE_QUOTES_TO_SILVER RESUME;
