-- Seed date dimension for 2020-2035

USE WAREHOUSE STOCK_WH;
USE DATABASE STOCK_DWH;

INSERT INTO DW.DIM_DATE (
  DATE_SK, CALENDAR_DATE, YEAR, QUARTER, MONTH, DAY, DAY_OF_WEEK, IS_WEEKEND
)
SELECT
  TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) AS DATE_SK,
  d AS CALENDAR_DATE,
  YEAR(d) AS YEAR,
  QUARTER(d) AS QUARTER,
  MONTH(d) AS MONTH,
  DAY(d) AS DAY,
  DAYOFWEEKISO(d) AS DAY_OF_WEEK,
  IFF(DAYOFWEEKISO(d) IN (6, 7), TRUE, FALSE) AS IS_WEEKEND
FROM (
  SELECT DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) AS d
  FROM TABLE(GENERATOR(ROWCOUNT => 5844))
)
WHERE d <= '2035-12-31'::DATE
  AND TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) NOT IN (
    SELECT DATE_SK FROM DW.DIM_DATE
  );
