-- BI-friendly enriched views built on top of DW fact tables
USE WAREHOUSE STOCK_WH;
USE DATABASE STOCK_DWH;

CREATE SCHEMA IF NOT EXISTS DW;

CREATE OR REPLACE VIEW DW.VW_FACT_QUOTE_1M_ENRICHED AS
WITH base AS (
  SELECT
    f.TICKER_SK,
    d.TICKER_CODE AS TICKER,
    f.BUCKET_MINUTE,
    f.OPEN_PRICE,
    f.HIGH_PRICE,
    f.LOW_PRICE,
    f.CLOSE_PRICE,
    f.VOLUME,
    f.TURNOVER,
    f.SOURCE_ROWS,
    LAG(f.CLOSE_PRICE) OVER (
      PARTITION BY f.TICKER_SK
      ORDER BY f.BUCKET_MINUTE
    ) AS PREV_CLOSE
  FROM DW.FACT_QUOTE_1M f
  JOIN DW.DIM_TICKER d
    ON d.TICKER_SK = f.TICKER_SK
   AND d.IS_CURRENT = TRUE
)
SELECT
  TICKER_SK,
  TICKER,
  BUCKET_MINUTE,
  OPEN_PRICE,
  HIGH_PRICE,
  LOW_PRICE,
  CLOSE_PRICE,
  VOLUME,
  TURNOVER,
  SOURCE_ROWS,
  COALESCE(PREV_CLOSE, OPEN_PRICE, CLOSE_PRICE) AS PREV_CLOSE,
  (CLOSE_PRICE - COALESCE(PREV_CLOSE, OPEN_PRICE, CLOSE_PRICE)) AS CHANGE_ABS,
  CASE
    WHEN COALESCE(PREV_CLOSE, OPEN_PRICE, 0) = 0 THEN 0
    ELSE ((CLOSE_PRICE - COALESCE(PREV_CLOSE, OPEN_PRICE, CLOSE_PRICE)) / COALESCE(PREV_CLOSE, OPEN_PRICE, CLOSE_PRICE)) * 100
  END AS PCT_CHANGE
FROM base;
