FROM nginx:1.25-alpine

RUN apk add --no-cache apache2-utils bash

ENV NGINX_USER=admin \
    NGINX_PASSWORD=changeme

COPY nginx/conf.d/bigdata-ui.conf /etc/nginx/conf.d/default.conf

# Create htpasswd file at build time
RUN htpasswd -bc /etc/nginx/.htpasswd "$NGINX_USER" "$NGINX_PASSWORD"

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]


