FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements-consumer.txt .
RUN pip install --no-cache-dir -r requirements-consumer.txt

# Copy consumer script
COPY kafka_to_postgres.py .

# Run consumer
CMD ["python", "-u", "kafka_to_postgres.py"]





